### ISSUE TITLE
Unable to find module 'puppetlabs-apache' on http://forge.puppetlabs.com

### ISSUE THREAD

**Issue by sherzberg** [thomasvandoren/puppet-pypi#5]
I am using librarian to try and install this package. The Modulefile has puppetlabs-apache as a dependency. Does it need to be puppetlabs/apache? I get "Unable to find module 'puppetlabs-apache' on http://forge.puppetlabs.com after executing librarian".

**Comment by thomasvandoren** [comment]
Puppet supports the hyphen delimiter, but the [docs](http://docs.puppetlabs.com/puppet/2.7/reference/modules_publishing.html#write-a-modulefile) do say to use a slash. I'll update the Modulefile.

Thanks!

**Comment by thomasvandoren** [comment]
Fixed in https://github.com/thomasvandoren/puppet-pypi/commit/8a813dd1444247f49b77b6c5231c821241564da5

**Comment by thomasvandoren** [comment]
The fix is now available on puppet forge in version 0.0.5. http://forge.puppetlabs.com/thomasvandoren/pypi/0.0.5
